# This method of generating Nix configuration borrows heavily from the nix-darwin project:
# https://github.com/nix-darwin/nix-darwin/blob/0d71cbf88d63e938b37b85b3bf8b238bcf7b39b9/modules/nix/default.nix

{ lib, ... }:

let
  inherit (lib) types;

  mkValueString =
    v:
    if v == null then
      ""
    else if builtins.isInt v then
      builtins.toString v
    else if builtins.isBool v then
      lib.boolToString v
    else if builtins.isFloat v then
      lib.strings.floatToString v
    else if builtins.isList v then
      builtins.toJSON v
    else if lib.isDerivation v then
      builtins.toString v
    else if builtins.isPath v then
      builtins.toString v
    else if builtins.isAttrs v then
      builtins.toJSON v
    else if builtins.isString v then
      v
    else if lib.strings.isCoercibleToString v then
      builtins.toString v
    else
      abort "The nix conf value ${lib.generators.toPretty { } v} can't be encoded";
  mkKeyValue = k: v: "${lib.escape [ "=" ] k} = ${mkValueString v}";

  semanticConfType =
    with types;
    let
      confAtom =
        nullOr (oneOf [
          bool
          int
          float
          str
          path
          package
        ])
        // {
          description = "Nix config atom (null, bool, int, float, str, path or package)";
        };
    in
    attrsOf (either confAtom (listOf confAtom));

  # Settings that Determinate Nix handles for you
  disallowedOptions = [
    "always-allow-substitutes"
    "bash-prompt-prefix"
    "netrc-file"
    "ssl-cert-file"
    "upgrade-nix-store-path-url"
  ];
in
{
  options.determinate-nix.customSettings = lib.mkOption {
    type = types.submodule {
      options = { };

      # Support "free-form" options
      freeformType = semanticConfType;
    };
  };

  config = lib.mkIf (config.determinate-nix.customSettings != { }) {
    assertions = [
      {
        assertion = lib.all (key: !lib.hasAttr key config.determinate-nix.customSettings) disallowedOptions;
        message = ''
          These settings are not allowed in `determinate-nix.customSettings`:
            ${lib.concatStringsSep ", " disallowedOptions}
        '';
      }
    ];

    environment.etc."nix/nix.custom.conf".text = lib.concatStringsSep "\n" (
      [
        "# This custom configuration file for Determinate Nix is generated by the determinate module for nix-darwin."
        "# Update your custom settings by changing your nix-darwin configuration, not by modifying this file directly."
        ""
      ]
      ++ lib.mapAttrsToList mkKeyValue config.determinate-nix.customSettings
    );
  };
}
