on:
  workflow_dispatch:
    inputs:
      reference-id:
        type: string
        required: true
      version:
        type: string
        required: true
      determinate-nixd-tag-name:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  propose-release:
    uses: DeterminateSystems/propose-release/.github/workflows/workflow.yml@main
    permissions:
      id-token: "write"
      contents: "write"
      pull-requests: write
    with:
      reference-id: ${{ inputs.reference-id }}
      version: ${{ inputs.version }}
      extra-commands-early: |
        sed -i "s#https://install.determinate.systems/determinate-nixd/tag/.*/#https://install.determinate.systems/determinate-nixd/tag/${{ inputs.determinate-nixd-tag-name }}/#" ./flake.nix
        git add flake.nix
        git commit -m "Update determinate-nixd binaries to ${{ inputs.determinate-nixd-tag-name }}"
